apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sheerwater-chat.fullname" . }}-pvc
  labels:
    {{- include "sheerwater-chat.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
